name: Node.js-build-cl
  on:
    push:
      branches:
        - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - run: npm cl
      - run: npm build
